import './globals.css'
import {barriecito} from './fonts';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-slate-900 max-h-screen overflow-x-hidden'>
        <div className={barriecito.className}>
          {children}
        </div>
        
        </body>
    </html>
  )
}
